### PR TITLE
Drop deprecated `implprefix=` usage.

### LINKED ISSUE #74: Pluggy version 1.0.0 breaks pysipp
```
conftest.py:3: in <module>
    import pysipp
/usr/local/lib/python3.9/dist-packages/pysipp/__init__.py:23: in <module>
    from . import launch, report, plugin, netplug, agent
/usr/local/lib/python3.9/dist-packages/pysipp/plugin.py:9: in <module>
    mng = pluggy.PluginManager('pysipp', implprefix='pysipp')
E   TypeError: __init__() got an unexpected keyword argument 'implprefix'
```

https://pluggy.readthedocs.io/en/latest/changelog.html#deprecations-and-removals

### PR DESCRIPTION
**Pull request by goodboy**
Was trying to let a hopeful new contrib take this very simple change on but it seems i'm not explaining the change well?

See the details in #74.

Fixes #74.

### CODE REVIEW

**Comment by goodboy** [comment]
Hmm I guess we don't have a CI run any more either?

Probably need a PR for GH actions I guess.

**Comment by linuxmaniac** [comment]
CI implemented at #83 and this commit is there

**Comment by linuxmaniac** [comment]
Already merged at e59ea0031f8ce530ac49848f768013ddeb952b1c

**Comment by goodboy** [comment]
@linuxmaniac thanks again 😄

**Pull request closed without merging**
