### PR TITLE
Added TLS params to command spec

### PR DESCRIPTION
**Pull request by dmbhatti**
Allows adding paths to TLS Certificate, Private Key and CRL file

### CODE REVIEW

**Review by goodboy — APPROVED** [review]
Sweet looks good!

**Comment by kontsaki** [comment]
this seems to be missing the spaces at the end of the string

**Comment by dmbhatti** [comment]
it does :(

**Comment by kontsaki** [comment]
maybe we can simplify command building to prevent these errors altogether, i will give it a try as soon as i grok current implementation.

**Comment by dmbhatti** [comment]
Ive made a new pull request with the added spaces.
Should have tested properly before making the first one

**Pull request merged**
