### PR TITLE
Feature/support disabling screen_file argument

### PR DESCRIPTION
**Pull request by y-luis**
Allow disabling `screen_file` argument.

### CODE REVIEW

**Comment by tgoodlet** [comment]
@y-luis do you mind squashing this history down to a single commit.
Lot of noise in that commit chain ;)

**Comment by y-luis** [comment]
Done ;)

**Comment by tgoodlet** [comment]
@y-luis awesome :+1: 

I'm just trying to remember (will look at the code later) exposing this in `Agent.__init__()` means the public apis in `pysipp/__init__.py` also have direct exposure right?

**Comment by y-luis** [comment]
This comes from using _pysipp_ with _sipp_ version 3.3 which does not support log files. The way this change can be used is passing the `log` argument to scenario creation:

```scen = pysipp.scenario(dirpath=temp_dir, logs=False)```

**Comment by tgoodlet** [comment]
@y-luis hmm I wonder if it's `sipp` version specific maybe we should have some logic to detect that and automatically disable logs - or at the least document this option in the readme.

**Comment by y-luis** [comment]
I agree @tgoodlet. I can document that in the README, but I do not know which is the minimum version supporting log files. Will have to research it.

**Comment by tgoodlet** [comment]
@y-luis hmm yeah maybe worth documenting as well.
`sipp` versions was not something that was scrutinized too much with this project - it was built on whatever the latest version was at the time.

**Comment by y-luis** [comment]
@tgoodlet, feature fixed to only disable `-screen_file` which is the only non-supported argument in SIPp < 3.5.0. Also, the description was included in the README.

**Comment by tgoodlet** [comment]
@y-luis awesome nice work :+1: 
Mind rebasing this onto master now that #41 is in - get a clean run and this is likely good to go!

**Comment by y-luis** [comment]
Thanks, @tgoodlet. Merged #41.

**Comment by y-luis** [comment]
`git rebase` done.

**Pull request merged**
