### PR TITLE
add github actions support

### PR DESCRIPTION
**Pull request by linuxmaniac**
As mentioned at #62 project needs to migrate CI to github actions

### CODE REVIEW

**Comment by linuxmaniac** [comment]
@goodboy I would love to see the project improve the actual situation. So, lets start with implementing the CI

**Comment by linuxmaniac** [comment]
> Do you have an example of this CI run working fully on your fork by chance?

I do, but for sure it's not passing

https://github.com/linuxmaniac/pysipp/actions/runs/3565669501/jobs/5991124740

```
============================= test session starts ==============================
  platform linux -- Python 3.8.14, pytest-7.2.0, pluggy-1.0.0
  cachedir: .tox/py38/.pytest_cache
  rootdir: /home/runner/work/pysipp/pysipp
  collected 59 items
  
  tests/test_agent.py ...............                                      [ 25%]
  tests/test_commands.py .....                                             [ 33%]
  tests/test_launcher.py ..                                                [ 37%]
  tests/test_loader.py ..                                                  [ 40%]
  tests/test_stack.py .F.................................                  [[100](https://github.com/linuxmaniac/pysipp/actions/runs/3565669501/jobs/5991124740#step:5:104)%]
  
  =================================== FAILURES ===================================
  ______________________________ test_confpy_hooks _______________________________
  
  scendir = '/home/runner/work/pysipp/pysipp/tests/scens/'
  
      def test_confpy_hooks(scendir):
          """Test that hooks included in a confpy file work
      
          Assertions here are based on predefined hooks
          """
          path, scen = list(pysipp.walk(scendir + "/default_with_confpy"))[0]
          assert scen.mod
          # ordering hook should reversed agents
          agents = list(scen.agents.values())
  >       assert agents[0].is_client()
  E       assert False
  E        +  where False = <bound method UserAgent.is_client of <pysipp.agent.UserAgent object at 0x7f0fa2228580>>()
  E        +    where <bound method UserAgent.is_client of <pysipp.agent.UserAgent object at 0x7f0fa2228580>> = <pysipp.agent.UserAgent object at 0x7f0fa2228580>.is_client
  
  tests/test_stack.py:47: AssertionError
  =============================== warnings summary ===============================
```

**Comment by linuxmaniac** [comment]
Here is a CI for previous [py27](https://github.com/SIPp/pysipp/compare/master...linuxmaniac:pysipp:vseva_ci_py27) but fails on the pypy2 environment

https://github.com/linuxmaniac/pysipp/actions/runs/3594127596

**Comment by goodboy** [comment]
Ok so maybe to just get this all going can we skip the `test_confpy_hooks` test which seems to be the common failure and then possibly also unrap the suite from using `tox`.

If you're uncomfortable try that lmk 😸

**Comment by linuxmaniac** [comment]
@goodboy  with this last version, all OK

https://github.com/linuxmaniac/pysipp/actions/runs/3599894859

**Comment by goodboy** [comment]
@linuxmaniac nice work, maybe make a followup issue for those tests as well so we don't forget about them 😂

**Pull request merged**
