### PR TITLE
0.1.0 release

### PR DESCRIPTION
**Pull request by goodboy**
An attempt at getting #42 going!

Things to do after this gets merged:
- start a release ledger
- [build out a distribution](https://packaging.python.org/tutorials/packaging-projects/#generating-distribution-archives)
- test [uploading it with `twine`](https://packaging.python.org/tutorials/packaging-projects/#uploading-the-distribution-archives) to https://test.pypi.org/
- get some peeps to [test installation from the test server](https://packaging.python.org/tutorials/packaging-projects/#installing-your-newly-uploaded-package)
- upload the final product to https://pypi.org

Note this will be our first release in general but our last supporting python 2.7. Once this lands and the package has been tested by all I'll be moving forward with stripping out py2.7 hindrances which should get us a bunch of cool stuff going forward!

### CODE REVIEW

**Comment by goodboy** [comment]
Draft release [is up on `test.pypi`](https://test.pypi.org/project/pysipp/).

Can everyone try a download and test of it:
`pip install --index-url https://test.pypi.org/simple/ --no-deps pysipp`

Note you'll have to install all the deps manually with `pip` since most of them aren't hosted on the test server.

ping @y-luis @luismartingil

**Comment by goodboy** [comment]
@vodik @wdoekes any thoughts or should I just get this moving?

Also what does everyone think for a changelog/release system?
The `pytest` bois i work with all use [towncrier](https://github.com/hawkowl/towncrier) but I'm open to trying whatever the hip new thing is.

**Comment by wdoekes** [comment]
Sorry, no time to review these weeks.

Just get it moving :)

One can always make a new release if things are amiss.

**Comment by goodboy** [comment]
Lol I guess I dropped the ball on this one.

Did anyone ever test the test server?

I'm happy to merge and upload.

Lurkers need to yell at us here!

**Comment by goodboy** [comment]
https://pypi.org/project/pysipp/

If it blows up open an issue and we'll make another minor release.

**Pull request merged**
