### PR TITLE
Add `auth_username` in command sipp_spec

### PR DESCRIPTION
**Pull request by laerus**
Hello, does something like this make sense? 

at the moment the only way to configure the username for authentication is to use the `-s` service option
but there are cases that one may want these two to be different

### CODE REVIEW

**Comment by goodboy** [comment]
@laerus if this is a valid option then it looks fine to me.
Can you provide a test demonstrating it's use and validating that it works?

Thanks!

**Comment by laerus** [comment]
@goodboy this is a valid option according to `sipp --help` 

without this patch one must hardcode the username in the`[authentication]` [keyword](https://sipp.readthedocs.io/en/v3.6.0/scenarios/keywords.html#authentication) in the xml scenario. this just complements the `auth_password` (`-ap` sipp argument).

do you mean you want me to write a test in `tests/tests_command.py` or provide an example here with `sipp` ?

if the later, when i use `sipp` i can just a bare `[authenication]` xml keyword in the scenario and provide the username/password with the `-au` and `-ap` arguments respectively but when i use the same scenario with pysipp i must hardcode the username in the xml keyword `[authentication username=test]`

**Comment by goodboy** [comment]
>do you mean you want me to write a test in tests/tests_command.py or provide an example here with sipp ?

@laerus the latter at least would be good but with `pysipp` actually! I think starting to document how to accomplish practical things most people will require is quite handy even if just a small section in the readme.

Having a specific test for the flags I guess isn't that important since we already have tests for other standard options and it's just using the built-in machinery to render the string passed to `sipp`. 

What would be great is a more *end-to-end* test that ran a small authentication scenario demonstrating that these flags indeed work when passed to `sipp` in a practical context. I won't require that you write that up here but maybe it's something for a further issue/task?

**Comment by laerus** [comment]
i've added a section for this feature in README

> What would be great is a more end-to-end test

i can open another PR for this, should this go in `tests/test_agent.py` ?

**Comment by goodboy** [comment]
>i can open another PR for this, should this go in tests/test_agent.py ?

@laerus yes please!
Feel free to open an issue to track it until you have a PR going.
Thanks for this work!

**Pull request merged**
