### PR TITLE
Proxyaddr fix

### LINKED ISSUE #36: proxyaddr ignored
When `dirpath` and `proxyaddr` are set, the last is ignored because of its indentation.

### PR DESCRIPTION
**Pull request by goodboy**
Redo of #35.
Fixes #36 and hopefully #39.

@y-luis @access2praveen mind having a quick look / trying this out.

### CODE REVIEW

**Comment by y-luis** [comment]
@tgoodlet, tested OK from my side 👍

**Comment by tgoodlet** [comment]
Huh, interesting `pypy` failures. I'll have to check that out manually.

**Comment by luismartingil** [comment]
@goodboy Can we maybe use `pluggy-0.11.0`? Looks like it does the trick (`python 2.7`):

```
platform linux2 -- Python 2.7.5, pytest-4.5.0, py-1.8.0, pluggy-0.11.0
rootdir: /Volumes/data/pysipp
collected 55 items

tests/test_agent.py ...........                                                                                                                                                                              [ 20%]
tests/test_commands.py .....                                                                                                                                                                                 [ 29%]
tests/test_launcher.py ..                                                                                                                                                                                    [ 32%]
tests/test_loader.py ..                                                                                                                                                                                      [ 36%]
tests/test_stack.py ...................................
```

**Comment by goodboy** [comment]
Huh very good point @luismartingil.
Just pushed a commit to use latest `pluggy`.

**Comment by goodboy** [comment]
Hmm seems to still be failing @luismartingil even with that version. I don't have `pypy` set up locally atm. Did you actually test with the version that's running on travis?

**Comment by goodboy** [comment]
Dropped `pypy` in CI as per #52 and #51 to get this moving!

**Pull request merged**
