### PR TITLE
merge master on drop_py27

### PR DESCRIPTION
**Pull request by kontsaki**
this fixes the conflicts i've introduced by formatting with black

### CODE REVIEW

**Comment by goodboy** [comment]
@kontsaki the problem now is this reverts changes from the target branch (such as the email change) among other things.

Merging back from master like this just basically takes all the conflicts wholesale from master instead of actually resolving them.

This is why I said the rebase needs to be done - merging branches back like this also leave a pretty ugly looking git history.

**Comment by kontsaki** [comment]
> the problem now is this reverts changes from the target branch (such as the email change) among other things.

@goodboy do you mean that there are changes that are missing?

sorry, i haven't used rebase much to understand what's the difference with merging except merge commits

**Comment by kontsaki** [comment]
i'm reading that rebasing is not good for already published branches, it will require a force push if i understand correctly

**Comment by goodboy** [comment]
> i'm reading that rebasing is not good for already published branches, it will require a force push if i understand correctly

Yes nothing wrong with this imo. IIRC there was something distinctly missing last time I looked at this diff; it's the cognative load of looking through so many non-functional changes that makes me put this kinda thing off 😉 

I remember at the least the new email in `setup.py` looks like it was lost, there might be more?

I have to go through this in detail I think unfortunately...

Again this is why I'd recommend in the future making functional changes separate from broad style patches.

**Comment by kontsaki** [comment]
setup.py email is the same at master and #55

**Comment by goodboy** [comment]
Ok we'll do it your way and try merging this because what I thought was off isn't 😂 

I'm going to push up a clone of the branch for #63 to see how things look after merging this into that branch.

**Comment by kontsaki** [comment]
ping :)

**Comment by goodboy** [comment]
Aight [pushed up a clone of `drop_py27`](https://github.com/SIPp/pysipp/tree/drop_py27_copy_without_black_changes) in case we run into any issues 🕶️.

Gonna merge this!

**Pull request merged**
