### PR TITLE
remove deprecation warnings 

### PR DESCRIPTION
**Pull request by linuxmaniac**

### CODE REVIEW

**Comment by linuxmaniac** [comment]
@goodboy rebased to trigger CI, all OK

**Comment by goodboy** [comment]
@linuxmaniac again looks great to me.

Can we rebase this onto latest `master` and see the CI run?

Then I can give it a proper review 🏄🏼

**Review by goodboy — APPROVED** [review]
Ye, reviewed quickly anyway and looks good.

**Comment by linuxmaniac** [comment]
@goodboy rebased

**Review by goodboy — APPROVED** [review]
Looks good.

Glad to see the module loading updated and some tests to match 🚀

**Pull request merged**
